"""Add party_affiliation field to MP model

Revision ID: afaecddde32c
Revises: 708ab958b23c
Create Date: 2023-12-14 23:49:15.890605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afaecddde32c'
down_revision: Union[str, None] = '708ab958b23c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mps', sa.Column('party_affiliation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mps', 'party_affiliation')
    # ### end Alembic commands ###
